server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 80

logging:
  level:
    root: INFO #모든 라이브러리는 INFO 이상만 출력
    com.tenco: DEBUG # 내 프로젝트는 DEBUG

spring:
  mustache:
    servlet:
      # 머스태치 템플릿 엔진에서 request 객체와 세션 객체에 접근할 수 있도록 허용
      expose-session-attributes: true
      expose-request-attributes: true
  #데이터베이스 연결 설정 (MySQL)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=Asia/Seoul
    username: root
    password: root
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
#    username: sa
#    password:
  h2:
    console:
      enabled: true

#     초기 데이터 설정
  sql:
    init:
      mode: always
      data-locations:
        - classpath:db/data.sql

  jpa:
    # Open Session In View --> false 로 설정
    # true (기본값) -> 뷰 랜더링까지 DB 세션 유지됨(LAZY 로딩 가능)
    # false : 트랜잭션 종료 시 DB 세션 종료 (Controller, View에서 LAZY 로딩 불가)
    # false 사용 시  Service 단에서 필요한 데이터를 모두 조회하고 응답 시에 DTO 설계방식으로 처리한다.
    open-in-view: false
    hibernate:
      # create 애플리케이션 시작 시 테이블 새로 생성
      # 기존 데이터는 모두 삭제됨 (개발용)
      ddl-auto: create
    # SQL 쿼리를 콘솔에 출력 (개발용)
    show-sql: true
    properties:
      hibernate:
        # SQL 쿼리를 보기 좋게 포맷팅 해주는 설정
        format_sql: true
        # N + 1 문제를 완화하기위한 완충 장치 설정
        # 기본 WHERE 절에서 in 절 (in 쿼리) 로 변경해준다.
        default_batch_fetch_size: 10
    # data.sql 파일을 하이버네이트 초기화 이후 실행
    defer-datasource-initialization: true